### PR TITLE
#14 Implement chart animation

### PR DESCRIPTION
**Pull request by irina-chernik**
Hi @mahowa, this is demo version of animation changes for charts.
If this version is OK, then I'll update PR to be up-to-date and refactor code.

### CODE REVIEW

**Comment by irina-chernik** [comment]
covid-states

**Comment by irina-chernik** [comment]
This is how animation works, but there is an issue with gradient. It's hard to animate.
covid-accum-bug

**Comment by irina-chernik** [comment]
I know that this version has a lot of code changes. And probably because of this may be not accepted.
So before spending more time on refactoring and fixing last issue I wanted to know if this is needed.

_Explanation of code changes:_
Transition from one chart line to another can be made when the data updates. It needs previous chart state. So I moved creation of svg elements to init function and createLineChart function now has only data changes. This data changes trigger transition from one line to another.
Accum checkbox doesn't change data array. Thus the update for filteredData and adding of lineMap attribute. It sets the same name for deaths and cases lines but uses different data params to generate filteredData.
Here is an example:
https://www.d3-graph-gallery.com/graph/line_change_data.html

**Comment by irina-chernik** [comment]
P.S: while coding noticed this comment
d3
        .axisBottom(xScale)
        .tickFormat((t) => d3.timeFormat("%B")(t))
        .tickSize(0)
        .ticks(numMonths) **// todo figure out why this isnt working the way we want**
And as well stumbled upon this article http://www.d3noob.org/2016/08/changing-number-of-ticks-on-axis-in.html
Which mentions such thing
_Intervals have a number of standard units (including UTC time) such as ... d3.timeSaturday : A week starting on Saturday
d3.timeMonth : Months starting on the 1st of the month_
Maybe it is applied to dateAxis as well.

**Comment by mahowa** [comment]
This is great can you fix the conflicts? Then i will merge

**Comment by irina-chernik** [comment]
I can fix merge conflicts. The only trouble is gradient. There is an issue when using cumulative checkbox - gradient area is not updating. Couldn't figure out what's the problem yet. So this one is in question.

**Comment by irina-chernik** [comment]
@mahowa Done, finally found and fixed issue with checkbox change.

**Comment by mahowa** [comment]
This is great @irina-chernik would you want to try to animate the area fill as well

**Pull request merged**
