### PR TITLE
Issue: make the chart responsive 

### PR DESCRIPTION
**Pull request by pedchenkoroman**
What has been done: 
1. Use viewBox attribute instead of width and height

### CODE REVIEW

**Comment by mahowa** [comment]
#16

**Comment by mahowa** [comment]
This is a very creative way of solving the problem so kudos to that. 

The issue is when we resize this way. the labels get smaller and unreadable

I would suggest that you try to redraw on a resize event. I understand this is performance intensive so anyway you can optimize it would work. Or if you have another solution that would work too.

Thanks for contributing @pedchenkoroman

**Review by mahowa — CHANGES_REQUESTED** [review]
I think we are looking to update on resize event so that the text is not resized with the chart

**Comment by pedchenkoroman** [comment]
Okay, thank you for giving a heads up @mahowa . I'm going to pick up a new issue and try to contribute.

**Pull request closed without merging**
